// Examples of some ElasticSearch requests.

#
# View nodes status
#
http://localhost:8080
GET /admin/metrics

POST /api/chirps
{
  "body": "I had something interesting for breakfast"
}

GET /api/chirps

POST /api/chirps
{
  "body": "What about second breakfast?"
}

POST /api/chirps
{
  "body": "Supper? Dinner? Do you know about those?"
}

GET /api/chirps
